In [ ]:
Explanation:

    Creating Arrays: np.array() is used to create numpy arrays.
    Array Shape and Reshape: shape returns the dimensions of the array, and reshape() changes the shape of the array.
    Array Arithmetic Operations: You can perform element-wise operations directly with arrays.
    Element-wise Operations: Operations like multiplication can be performed element-wise.
    Basic Statistics: Functions like mean(), sum(), max(), and min() provide statistical operations.
    Matrix Multiplication: dot() is used for matrix multiplication.
    Transpose of a Matrix: transpose() or .T is used to transpose a matrix.
    Slicing and Indexing: Arrays can be sliced and indexed to extract specific elements.
    Boolean Masking: Conditions can be applied to arrays to create masks, which can then be used to filter elements.
    Concatenation: concatenate() joins arrays along an existing axis.
  
This program gives an overview of many common operations you can perform with NumPy arrays.

In [1]:
import numpy as np

# 1. Creating Arrays
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3], [4, 5, 6]])

print("Array a:")
print(a)
print("Array b:")
print(b)

# 2. Array Shape and Reshape
print("\nShape of a:", a.shape)
print("Shape of b:", b.shape)

reshaped_b = b.reshape(3, 2)
print("\nReshaped b (3x2):")
print(reshaped_b)

# 3. Array Arithmetic Operations
c = a + 2
d = a * 3
e = b + a

print("\nArray c (a + 2):")
print(c)
print("Array d (a * 3):")
print(d)
print("Array e (b + a):")
print(e)

# 4. Element-wise Operations
f = a * b[0]  # Element-wise multiplication with the first row of b
print("\nElement-wise multiplication of a and b[0]:")
print(f)

# 5. Basic Statistics
print("\nMean of b:", np.mean(b))
print("Sum of b:", np.sum(b))
print("Max of b:", np.max(b))
print("Min of b:", np.min(b))

# 6. Matrix Multiplication
g = np.dot(b, reshaped_b)
print("\nMatrix multiplication of b and reshaped_b:")
print(g)

# 7. Transpose of a Matrix
print("\nTranspose of b:")
print(np.transpose(b))

# 8. Slicing and Indexing
print("\nSlicing the first row of b:")
print(b[0, :])

print("\nExtracting a sub-array (first two columns):")
print(b[:, :2])

# 9. Boolean Masking
mask = b > 3
print("\nBoolean mask of b (values greater than 3):")
print(mask)
print("Applying mask to b:")
print(b[mask])

# 10. Concatenation
h = np.concatenate((a, a), axis=0)
print("\nConcatenation of a with itself:")
print(h)

# 11. Stacking
vstacked = np.vstack((a, a))
hstacked = np.hstack((a, a))

print("\nVertical stacking of a with itself:")
print(vstacked)
print("Horizontal stacking of a with itself:")
print(hstacked)


Array a:
[1 2 3]
Array b:
[[1 2 3]
 [4 5 6]]

Shape of a: (3,)
Shape of b: (2, 3)

Reshaped b (3x2):
[[1 2]
 [3 4]
 [5 6]]

Array c (a + 2):
[3 4 5]
Array d (a * 3):
[3 6 9]
Array e (b + a):
[[2 4 6]
 [5 7 9]]

Element-wise multiplication of a and b[0]:
[1 4 9]

Mean of b: 3.5
Sum of b: 21
Max of b: 6
Min of b: 1

Matrix multiplication of b and reshaped_b:
[[22 28]
 [49 64]]

Transpose of b:
[[1 4]
 [2 5]
 [3 6]]

Slicing the first row of b:
[1 2 3]

Extracting a sub-array (first two columns):
[[1 2]
 [4 5]]

Boolean mask of b (values greater than 3):
[[False False False]
 [ True  True  True]]
Applying mask to b:
[4 5 6]

Concatenation of a with itself:
[1 2 3 1 2 3]

Vertical stacking of a with itself:
[[1 2 3]
 [1 2 3]]
Horizontal stacking of a with itself:
[1 2 3 1 2 3]


In [ ]:
# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily'],
    'Age': [25, 30, None, 28, 24],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
    'Math_Score': [85, 92, 78, 88, 76],
    'Science_Score': [90, None, 85, 92, 88],
    'Passed_Exam': ['Yes', 'Yes', 'No', 'Yes', 'No']
}